#!/bin/bash

echo "Original upload"
git add .
git commit -m "$1"
git push -u origin master

echo "Copy.."
sudo cp ComicDB.mwb /var/www/html/TinyComicCMS/ComicDB.mwb
sudo cp .gitignore /var/www/html/TinyComicCMS/.gitignore
sudo cp index.html /var/www/html/TinyComicCMS/index.html
sudo cp LICENSE /var/www/html/TinyComicCMS/LICENSE
sudo cp README.md /var/www/html/TinyComicCMS/README.md
sudo cp Requirements_and_Installation.txt /var/www/html/TinyComicCMS/Requirements_and_Installation.txt
sudo cp upload /var/www/html/TinyComicCMS/upload_from_original_dir
sudo cp -r page/* /var/www/html/TinyComicCMS/page/
sudo cp -r assets/* /var/www/html/TinyComicCMS/assets/

echo "Copy upload"
cd /var/www/html/TinyComicCMS/
sudo ./upload_TCC "$1"

cd /var/www/html/StarForce
echo "Done."



